use_frameworks!

platform :ios, '9.0'

target 'MushengLoginMoudle_Example' do
  pod 'MushengLoginMoudle', :path => '../'

  target 'MushengLoginMoudle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
